// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns a greeting string",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Returns a greeting string",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login with Google access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with Google access token",
                "parameters": [
                    {
                        "description": "Provider access token payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ProviderLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Issued token pair",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenPairResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh access/refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access/refresh tokens",
                "parameters": [
                    {
                        "description": "Refresh token payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokensRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New token pair",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenPairResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/switch-team": {
            "post": {
                "security": [
                    {
                        "jwt": []
                    }
                ],
                "description": "Switch active team and get new tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Switch active team and get new tokens",
                "parameters": [
                    {
                        "description": "Switch team payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SwitchTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New token pair with teamId",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenPairResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/debug/users/plan": {
            "post": {
                "description": "Debug: update user personal plan (free|pro)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "debug"
                ],
                "summary": "Debug: update user personal plan (free|pro)",
                "parameters": [
                    {
                        "description": "Update plan payload (debug only)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/debug.UpdateUserPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Plan updated",
                        "schema": {
                            "$ref": "#/definitions/debug.UpdateUserPlanResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not allowed in production",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "security": [
                    {
                        "jwt": []
                    }
                ],
                "description": "List my projects",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "List my projects",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 15,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page index",
                        "name": "index",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (active, archived)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "newest",
                        "description": "Sort order (newest, oldest)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Project list",
                        "schema": {
                            "$ref": "#/definitions/project.ListProjectsResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "jwt": []
                    }
                ],
                "description": "Create project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Create project",
                "parameters": [
                    {
                        "description": "Project creation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.CreateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created project",
                        "schema": {
                            "$ref": "#/definitions/project.ProjectResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Project limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Project conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{id}": {
            "put": {
                "security": [
                    {
                        "jwt": []
                    }
                ],
                "description": "Update project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Update project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Project update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.UpdateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated project",
                        "schema": {
                            "$ref": "#/definitions/project.ProjectResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Project conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{id}/members": {
            "post": {
                "security": [
                    {
                        "jwt": []
                    }
                ],
                "description": "Add project member (owner only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Add project member (owner only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add member payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.AddMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Member added",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{id}/members/remove": {
            "post": {
                "security": [
                    {
                        "jwt": []
                    }
                ],
                "description": "Remove project member (owner only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Remove project member (owner only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Remove member payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.RemoveMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Member removed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams": {
            "post": {
                "security": [
                    {
                        "jwt": []
                    }
                ],
                "description": "Create a team (org workspace)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Create a team (org workspace)",
                "parameters": [
                    {
                        "description": "Team creation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/team.CreateTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Team created",
                        "schema": {
                            "$ref": "#/definitions/team.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "jwt": []
                    }
                ],
                "description": "Get current user profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "Current user",
                        "schema": {
                            "$ref": "#/definitions/user.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "jwt": []
                    }
                ],
                "description": "Update current user profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update current user profile",
                "parameters": [
                    {
                        "description": "User update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated user",
                        "schema": {
                            "$ref": "#/definitions/user.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created user and JWT token",
                        "schema": {
                            "$ref": "#/definitions/user.RegisterUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.ProviderLoginRequest": {
            "description": "Provider access token payload",
            "type": "object",
            "required": [
                "accessToken"
            ],
            "properties": {
                "accessToken": {
                    "type": "string",
                    "minLength": 1
                },
                "teamId": {
                    "type": "string"
                }
            }
        },
        "auth.RefreshTokensRequest": {
            "description": "Refresh token payload",
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "auth.SwitchTeamRequest": {
            "description": "Switch team payload",
            "type": "object",
            "required": [
                "teamId"
            ],
            "properties": {
                "teamId": {
                    "type": "string"
                }
            }
        },
        "auth.TokenPair": {
            "description": "Token pair response",
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIs..."
                },
                "refreshToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIs..."
                }
            }
        },
        "auth.TokenPairResponse": {
            "description": "Token pair wrapped in response envelope",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.TokenPair"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "debug.UpdateUserPlanRequest": {
            "description": "Update plan payload (debug only)",
            "type": "object",
            "required": [
                "plan"
            ],
            "properties": {
                "plan": {
                    "type": "string",
                    "enum": [
                        "free",
                        "pro"
                    ]
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "debug.UpdateUserPlanResponse": {
            "description": "Plan updated response",
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "debug.UpdateUserPlanResponseWrapper": {
            "description": "Update user plan response wrapped in response envelope",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/debug.UpdateUserPlanResponse"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "project.AddMemberRequest": {
            "description": "Add member payload",
            "type": "object",
            "required": [
                "role",
                "userId"
            ],
            "properties": {
                "role": {
                    "type": "string",
                    "enum": [
                        "owner",
                        "editor",
                        "viewer"
                    ]
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "project.CreateProjectRequest": {
            "description": "Project creation payload",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "defaultLanguage": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "project.ListProjectsMeta": {
            "description": "Pagination metadata",
            "type": "object",
            "properties": {
                "hasNext": {
                    "type": "boolean"
                },
                "index": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalPageCount": {
                    "type": "integer"
                }
            }
        },
        "project.ListProjectsResponse": {
            "description": "Project list response",
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project.Project"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/project.ListProjectsMeta"
                }
            }
        },
        "project.ListProjectsResponseWrapper": {
            "description": "Project list wrapped in response envelope",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/project.ListProjectsResponse"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "project.Project": {
            "description": "Project details",
            "type": "object",
            "properties": {
                "archived": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "defaultLanguage": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "ownerId": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "project.ProjectResponse": {
            "description": "Project wrapped in response envelope",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/project.Project"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "project.RemoveMemberRequest": {
            "description": "Remove member payload",
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "project.UpdateProjectRequest": {
            "description": "Project update payload",
            "type": "object",
            "properties": {
                "defaultLanguage": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "response.ErrorResponse": {
            "description": "Error response structure",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "team.CreateTeamRequest": {
            "description": "Team creation payload",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "team.Team": {
            "description": "Team details",
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ownerId": {
                    "type": "string"
                },
                "personal": {
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "team.TeamResponse": {
            "description": "Team wrapped in response envelope",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/team.Team"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "user.RegisterUserRequest": {
            "description": "User registration payload",
            "type": "object",
            "required": [
                "email",
                "id"
            ],
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "plan": {
                    "type": "string"
                }
            }
        },
        "user.RegisterUserResponse": {
            "description": "Created user and JWT token",
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIs..."
                },
                "refreshToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIs..."
                },
                "user": {
                    "$ref": "#/definitions/user.User"
                }
            }
        },
        "user.RegisterUserResponseWrapper": {
            "description": "Registration response wrapped in response envelope",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.RegisterUserResponse"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "user.TeamInfo": {
            "description": "Team information",
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "canCreateProject": {
                    "type": "boolean"
                },
                "memberCount": {
                    "type": "integer"
                },
                "personal": {
                    "type": "boolean"
                },
                "plan": {
                    "type": "string"
                },
                "projectCount": {
                    "type": "integer"
                },
                "teamId": {
                    "type": "string"
                },
                "teamName": {
                    "type": "string"
                }
            }
        },
        "user.UpdateUserRequest": {
            "description": "User update payload",
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "plan": {
                    "type": "string"
                }
            }
        },
        "user.User": {
            "description": "User profile",
            "type": "object",
            "properties": {
                "activeTeamId": {
                    "type": "string"
                },
                "avatarUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "plan": {
                    "type": "string"
                },
                "teams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.TeamInfo"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "user.UserResponse": {
            "description": "User wrapped in response envelope",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/user.User"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
