// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (id, email, full_name, avatar_url, plan, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, full_name, avatar_url, plan, stripe_customer_id, team_id, created_at, updated_at
`

type CreateProfileParams struct {
	ID        pgtype.UUID      `json:"id"`
	Email     pgtype.Text      `json:"email"`
	FullName  pgtype.Text      `json:"full_name"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
	Plan      pgtype.Text      `json:"plan"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.AvatarUrl,
		arg.Plan,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, email, full_name, avatar_url, plan, stripe_customer_id, team_id, created_at, updated_at FROM profiles WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET 
    full_name = COALESCE($3, full_name),
    avatar_url = COALESCE($4, avatar_url),
    plan = COALESCE($5, plan),
    updated_at = $2
WHERE id = $1
RETURNING id, email, full_name, avatar_url, plan, stripe_customer_id, team_id, created_at, updated_at
`

type UpdateProfileParams struct {
	ID        pgtype.UUID      `json:"id"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	FullName  pgtype.Text      `json:"full_name"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
	Plan      pgtype.Text      `json:"plan"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.UpdatedAt,
		arg.FullName,
		arg.AvatarUrl,
		arg.Plan,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfileTeamID = `-- name: UpdateProfileTeamID :one
UPDATE profiles
SET team_id = $2, updated_at = $3
WHERE id = $1
RETURNING id, email, full_name, avatar_url, plan, stripe_customer_id, team_id, created_at, updated_at
`

type UpdateProfileTeamIDParams struct {
	ID        pgtype.UUID      `json:"id"`
	TeamID    pgtype.UUID      `json:"team_id"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateProfileTeamID(ctx context.Context, arg UpdateProfileTeamIDParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfileTeamID, arg.ID, arg.TeamID, arg.UpdatedAt)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
