// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectsByOwnerID = `-- name: CountProjectsByOwnerID :one
SELECT COUNT(*) FROM projects WHERE owner_id = $1 AND is_deleted = false
`

func (q *Queries) CountProjectsByOwnerID(ctx context.Context, ownerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByOwnerID, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id, name, description, slug, owner_id, default_language, languages,
    created_at, updated_at, is_deleted, archived
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, description, slug, owner_id, default_language, languages, created_at, updated_at, is_deleted, deleted_at, archived
`

type CreateProjectParams struct {
	ID              pgtype.UUID      `json:"id"`
	Name            string           `json:"name"`
	Description     pgtype.Text      `json:"description"`
	Slug            string           `json:"slug"`
	OwnerID         pgtype.UUID      `json:"owner_id"`
	DefaultLanguage pgtype.Text      `json:"default_language"`
	Languages       []string         `json:"languages"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	IsDeleted       bool             `json:"is_deleted"`
	Archived        bool             `json:"archived"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.OwnerID,
		arg.DefaultLanguage,
		arg.Languages,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsDeleted,
		arg.Archived,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.OwnerID,
		&i.DefaultLanguage,
		&i.Languages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.Archived,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, slug, owner_id, default_language, languages, created_at, updated_at, is_deleted, deleted_at, archived FROM projects WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.OwnerID,
		&i.DefaultLanguage,
		&i.Languages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.Archived,
	)
	return i, err
}

const getProjectsByIDs = `-- name: GetProjectsByIDs :many
SELECT id, name, description, slug, owner_id, default_language, languages, created_at, updated_at, is_deleted, deleted_at, archived FROM projects WHERE id = ANY($1::UUID[]) AND is_deleted = false
`

func (q *Queries) GetProjectsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.OwnerID,
			&i.DefaultLanguage,
			&i.Languages,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsByOwnerID = `-- name: GetProjectsByOwnerID :many
SELECT id, name, description, slug, owner_id, default_language, languages, created_at, updated_at, is_deleted, deleted_at, archived FROM projects WHERE owner_id = $1 AND is_deleted = false
`

func (q *Queries) GetProjectsByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.OwnerID,
			&i.DefaultLanguage,
			&i.Languages,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET 
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    default_language = COALESCE($5, default_language),
    languages = COALESCE($6, languages),
    slug = COALESCE($7, slug),
    updated_at = $2
WHERE id = $1 AND is_deleted = false
RETURNING id, name, description, slug, owner_id, default_language, languages, created_at, updated_at, is_deleted, deleted_at, archived
`

type UpdateProjectParams struct {
	ID              pgtype.UUID      `json:"id"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	Name            pgtype.Text      `json:"name"`
	Description     pgtype.Text      `json:"description"`
	DefaultLanguage pgtype.Text      `json:"default_language"`
	Languages       []string         `json:"languages"`
	Slug            pgtype.Text      `json:"slug"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.UpdatedAt,
		arg.Name,
		arg.Description,
		arg.DefaultLanguage,
		arg.Languages,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.OwnerID,
		&i.DefaultLanguage,
		&i.Languages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.Archived,
	)
	return i, err
}
