// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_memberships.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamMembership = `-- name: CreateTeamMembership :one
INSERT INTO team_memberships (id, team_id, user_id, role, joined_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, team_id, user_id, role, joined_at, created_at
`

type CreateTeamMembershipParams struct {
	ID        pgtype.UUID      `json:"id"`
	TeamID    pgtype.UUID      `json:"team_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Role      string           `json:"role"`
	JoinedAt  pgtype.Timestamp `json:"joined_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, createTeamMembership,
		arg.ID,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
		arg.CreatedAt,
	)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMembershipByUserAndTeam = `-- name: GetTeamMembershipByUserAndTeam :one
SELECT id, team_id, user_id, role, joined_at, created_at FROM team_memberships WHERE user_id = $1 AND team_id = $2
`

type GetTeamMembershipByUserAndTeamParams struct {
	UserID pgtype.UUID `json:"user_id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) GetTeamMembershipByUserAndTeam(ctx context.Context, arg GetTeamMembershipByUserAndTeamParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getTeamMembershipByUserAndTeam, arg.UserID, arg.TeamID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMembershipsByTeamIDs = `-- name: GetTeamMembershipsByTeamIDs :many
SELECT id, team_id, user_id, role, joined_at, created_at FROM team_memberships WHERE team_id = ANY($1::UUID[])
`

func (q *Queries) GetTeamMembershipsByTeamIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]TeamMembership, error) {
	rows, err := q.db.Query(ctx, getTeamMembershipsByTeamIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMembership
	for rows.Next() {
		var i TeamMembership
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMembershipsByUserID = `-- name: GetTeamMembershipsByUserID :many
SELECT id, team_id, user_id, role, joined_at, created_at FROM team_memberships WHERE user_id = $1
`

func (q *Queries) GetTeamMembershipsByUserID(ctx context.Context, userID pgtype.UUID) ([]TeamMembership, error) {
	rows, err := q.db.Query(ctx, getTeamMembershipsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMembership
	for rows.Next() {
		var i TeamMembership
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
