// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_members.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO team_members (
    id, project_id, user_id, role, invited_at, joined_at, invited_by, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, user_id, role, invited_at, joined_at, invited_by, created_at
`

type CreateTeamMemberParams struct {
	ID        pgtype.UUID      `json:"id"`
	ProjectID pgtype.UUID      `json:"project_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Role      string           `json:"role"`
	InvitedAt pgtype.Timestamp `json:"invited_at"`
	JoinedAt  pgtype.Timestamp `json:"joined_at"`
	InvitedBy pgtype.UUID      `json:"invited_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.InvitedAt,
		arg.JoinedAt,
		arg.InvitedBy,
		arg.CreatedAt,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeamMember = `-- name: DeleteTeamMember :exec
DELETE FROM team_members WHERE project_id = $1 AND user_id = $2
`

type DeleteTeamMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) error {
	_, err := q.db.Exec(ctx, deleteTeamMember, arg.ProjectID, arg.UserID)
	return err
}

const getTeamMemberByProjectAndUser = `-- name: GetTeamMemberByProjectAndUser :one
SELECT id, project_id, user_id, role, invited_at, joined_at, invited_by, created_at FROM team_members WHERE project_id = $1 AND user_id = $2
`

type GetTeamMemberByProjectAndUserParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMemberByProjectAndUser(ctx context.Context, arg GetTeamMemberByProjectAndUserParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMemberByProjectAndUser, arg.ProjectID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMembersByUserID = `-- name: GetTeamMembersByUserID :many
SELECT id, project_id, user_id, role, invited_at, joined_at, invited_by, created_at FROM team_members WHERE user_id = $1
`

func (q *Queries) GetTeamMembersByUserID(ctx context.Context, userID pgtype.UUID) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, getTeamMembersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.InvitedAt,
			&i.JoinedAt,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
