// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name, owner_id, avatar_url, personal, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, owner_id, created_at, updated_at, avatar_url, personal
`

type CreateTeamParams struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	OwnerID   pgtype.UUID      `json:"owner_id"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
	Personal  bool             `json:"personal"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.AvatarUrl,
		arg.Personal,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.Personal,
	)
	return i, err
}

const getPersonalTeamByUserID = `-- name: GetPersonalTeamByUserID :one
SELECT t.id, t.name, t.owner_id, t.created_at, t.updated_at, t.avatar_url, t.personal FROM teams t JOIN profiles p ON t.id = p.team_id WHERE p.id = $1 AND t.personal = TRUE
`

func (q *Queries) GetPersonalTeamByUserID(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getPersonalTeamByUserID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.Personal,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, owner_id, created_at, updated_at, avatar_url, personal FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.Personal,
	)
	return i, err
}

const getTeamByIDAndPersonal = `-- name: GetTeamByIDAndPersonal :one
SELECT id, name, owner_id, created_at, updated_at, avatar_url, personal FROM teams WHERE id = $1 AND personal = $2
`

type GetTeamByIDAndPersonalParams struct {
	ID       pgtype.UUID `json:"id"`
	Personal bool        `json:"personal"`
}

func (q *Queries) GetTeamByIDAndPersonal(ctx context.Context, arg GetTeamByIDAndPersonalParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByIDAndPersonal, arg.ID, arg.Personal)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.Personal,
	)
	return i, err
}

const getTeamMembershipCount = `-- name: GetTeamMembershipCount :one
SELECT COUNT(*) FROM team_memberships WHERE team_id = $1
`

func (q *Queries) GetTeamMembershipCount(ctx context.Context, teamID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTeamMembershipCount, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeamsByIDs = `-- name: GetTeamsByIDs :many
SELECT id, name, owner_id, created_at, updated_at, avatar_url, personal FROM teams WHERE id = ANY($1::UUID[])
`

func (q *Queries) GetTeamsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeamsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvatarUrl,
			&i.Personal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
