// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getProjects, getUsersMe, type Options, postAuthLogin, postAuthRefresh, postAuthSwitchTeam, postDebugUsersPlan, postProjects, postProjectsByIdMembers, postProjectsByIdMembersRemove, postTeams, postUsersRegister, putProjectsById, putUsersMe } from '../sdk.gen';
import type { GetProjectsData, GetProjectsError, GetProjectsResponse, GetUsersMeData, GetUsersMeError, GetUsersMeResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostAuthRefreshData, PostAuthRefreshError, PostAuthRefreshResponse, PostAuthSwitchTeamData, PostAuthSwitchTeamError, PostAuthSwitchTeamResponse, PostDebugUsersPlanData, PostDebugUsersPlanError, PostDebugUsersPlanResponse, PostProjectsByIdMembersData, PostProjectsByIdMembersError, PostProjectsByIdMembersRemoveData, PostProjectsByIdMembersRemoveError, PostProjectsByIdMembersRemoveResponse, PostProjectsByIdMembersResponse, PostProjectsData, PostProjectsError, PostProjectsResponse, PostTeamsData, PostTeamsError, PostTeamsResponse, PostUsersRegisterData, PostUsersRegisterError, PostUsersRegisterResponse, PutProjectsByIdData, PutProjectsByIdError, PutProjectsByIdResponse, PutUsersMeData, PutUsersMeError, PutUsersMeResponse } from '../types.gen';

/**
 * Login with Google access token
 *
 * Login with Google access token
 */
export const postAuthLoginMutation = (options?: Partial<Options<PostAuthLoginData>>): UseMutationOptions<PostAuthLoginResponse, PostAuthLoginError, Options<PostAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLoginResponse, PostAuthLoginError, Options<PostAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Refresh access/refresh tokens
 *
 * Refresh access/refresh tokens
 */
export const postAuthRefreshMutation = (options?: Partial<Options<PostAuthRefreshData>>): UseMutationOptions<PostAuthRefreshResponse, PostAuthRefreshError, Options<PostAuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<PostAuthRefreshResponse, PostAuthRefreshError, Options<PostAuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Switch active team and get new tokens
 *
 * Switch active team and get new tokens
 */
export const postAuthSwitchTeamMutation = (options?: Partial<Options<PostAuthSwitchTeamData>>): UseMutationOptions<PostAuthSwitchTeamResponse, PostAuthSwitchTeamError, Options<PostAuthSwitchTeamData>> => {
    const mutationOptions: UseMutationOptions<PostAuthSwitchTeamResponse, PostAuthSwitchTeamError, Options<PostAuthSwitchTeamData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthSwitchTeam({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Debug: update user personal plan (free|pro)
 *
 * Debug: update user personal plan (free|pro)
 */
export const postDebugUsersPlanMutation = (options?: Partial<Options<PostDebugUsersPlanData>>): UseMutationOptions<PostDebugUsersPlanResponse, PostDebugUsersPlanError, Options<PostDebugUsersPlanData>> => {
    const mutationOptions: UseMutationOptions<PostDebugUsersPlanResponse, PostDebugUsersPlanError, Options<PostDebugUsersPlanData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postDebugUsersPlan({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getProjectsQueryKey = (options?: Options<GetProjectsData>) => createQueryKey('getProjects', options);

/**
 * List my projects
 *
 * List my projects
 */
export const getProjectsOptions = (options?: Options<GetProjectsData>) => queryOptions<GetProjectsResponse, GetProjectsError, GetProjectsResponse, ReturnType<typeof getProjectsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProjects({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProjectsQueryKey(options)
});

/**
 * Create project
 *
 * Create project
 */
export const postProjectsMutation = (options?: Partial<Options<PostProjectsData>>): UseMutationOptions<PostProjectsResponse, PostProjectsError, Options<PostProjectsData>> => {
    const mutationOptions: UseMutationOptions<PostProjectsResponse, PostProjectsError, Options<PostProjectsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postProjects({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update project
 *
 * Update project
 */
export const putProjectsByIdMutation = (options?: Partial<Options<PutProjectsByIdData>>): UseMutationOptions<PutProjectsByIdResponse, PutProjectsByIdError, Options<PutProjectsByIdData>> => {
    const mutationOptions: UseMutationOptions<PutProjectsByIdResponse, PutProjectsByIdError, Options<PutProjectsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putProjectsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Add project member (owner only)
 *
 * Add project member (owner only)
 */
export const postProjectsByIdMembersMutation = (options?: Partial<Options<PostProjectsByIdMembersData>>): UseMutationOptions<PostProjectsByIdMembersResponse, PostProjectsByIdMembersError, Options<PostProjectsByIdMembersData>> => {
    const mutationOptions: UseMutationOptions<PostProjectsByIdMembersResponse, PostProjectsByIdMembersError, Options<PostProjectsByIdMembersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postProjectsByIdMembers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remove project member (owner only)
 *
 * Remove project member (owner only)
 */
export const postProjectsByIdMembersRemoveMutation = (options?: Partial<Options<PostProjectsByIdMembersRemoveData>>): UseMutationOptions<PostProjectsByIdMembersRemoveResponse, PostProjectsByIdMembersRemoveError, Options<PostProjectsByIdMembersRemoveData>> => {
    const mutationOptions: UseMutationOptions<PostProjectsByIdMembersRemoveResponse, PostProjectsByIdMembersRemoveError, Options<PostProjectsByIdMembersRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postProjectsByIdMembersRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create a team (org workspace)
 *
 * Create a team (org workspace)
 */
export const postTeamsMutation = (options?: Partial<Options<PostTeamsData>>): UseMutationOptions<PostTeamsResponse, PostTeamsError, Options<PostTeamsData>> => {
    const mutationOptions: UseMutationOptions<PostTeamsResponse, PostTeamsError, Options<PostTeamsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postTeams({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUsersMeQueryKey = (options?: Options<GetUsersMeData>) => createQueryKey('getUsersMe', options);

/**
 * Get current user profile
 *
 * Get current user profile
 */
export const getUsersMeOptions = (options?: Options<GetUsersMeData>) => queryOptions<GetUsersMeResponse, GetUsersMeError, GetUsersMeResponse, ReturnType<typeof getUsersMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsersMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersMeQueryKey(options)
});

/**
 * Update current user profile
 *
 * Update current user profile
 */
export const putUsersMeMutation = (options?: Partial<Options<PutUsersMeData>>): UseMutationOptions<PutUsersMeResponse, PutUsersMeError, Options<PutUsersMeData>> => {
    const mutationOptions: UseMutationOptions<PutUsersMeResponse, PutUsersMeError, Options<PutUsersMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putUsersMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register a new user
 *
 * Register a new user
 */
export const postUsersRegisterMutation = (options?: Partial<Options<PostUsersRegisterData>>): UseMutationOptions<PostUsersRegisterResponse, PostUsersRegisterError, Options<PostUsersRegisterData>> => {
    const mutationOptions: UseMutationOptions<PostUsersRegisterResponse, PostUsersRegisterError, Options<PostUsersRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postUsersRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
