// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { appControllerGetHello, authControllerLoginWithProvider, authControllerRefreshTokens, type Options, projectControllerAddMember, projectControllerCreateProject, projectControllerListProjects, projectControllerRemoveMember, projectControllerUpdateProject, userControllerGetMe, userControllerRegister, userControllerUpdateMe } from '../sdk.gen';
import type { AppControllerGetHelloData, AppControllerGetHelloResponse, AuthControllerLoginWithProviderData, AuthControllerLoginWithProviderError, AuthControllerLoginWithProviderResponse, AuthControllerRefreshTokensData, AuthControllerRefreshTokensError, AuthControllerRefreshTokensResponse, ProjectControllerAddMemberData, ProjectControllerAddMemberError, ProjectControllerAddMemberResponse, ProjectControllerCreateProjectData, ProjectControllerCreateProjectError, ProjectControllerCreateProjectResponse, ProjectControllerListProjectsData, ProjectControllerListProjectsResponse, ProjectControllerRemoveMemberData, ProjectControllerRemoveMemberError, ProjectControllerRemoveMemberResponse, ProjectControllerUpdateProjectData, ProjectControllerUpdateProjectError, ProjectControllerUpdateProjectResponse, UserControllerGetMeData, UserControllerGetMeResponse, UserControllerRegisterData, UserControllerRegisterError, UserControllerRegisterResponse, UserControllerUpdateMeData, UserControllerUpdateMeError, UserControllerUpdateMeResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const appControllerGetHelloQueryKey = (options?: Options<AppControllerGetHelloData>) => createQueryKey('appControllerGetHello', options);

/**
 * Health check
 */
export const appControllerGetHelloOptions = (options?: Options<AppControllerGetHelloData>) => queryOptions<AppControllerGetHelloResponse, DefaultError, AppControllerGetHelloResponse, ReturnType<typeof appControllerGetHelloQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await appControllerGetHello({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: appControllerGetHelloQueryKey(options)
});

/**
 * Login with Google access token
 */
export const authControllerLoginWithProviderMutation = (options?: Partial<Options<AuthControllerLoginWithProviderData>>): UseMutationOptions<AuthControllerLoginWithProviderResponse, AuthControllerLoginWithProviderError, Options<AuthControllerLoginWithProviderData>> => {
    const mutationOptions: UseMutationOptions<AuthControllerLoginWithProviderResponse, AuthControllerLoginWithProviderError, Options<AuthControllerLoginWithProviderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerLoginWithProvider({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Refresh access/refresh tokens
 */
export const authControllerRefreshTokensMutation = (options?: Partial<Options<AuthControllerRefreshTokensData>>): UseMutationOptions<AuthControllerRefreshTokensResponse, AuthControllerRefreshTokensError, Options<AuthControllerRefreshTokensData>> => {
    const mutationOptions: UseMutationOptions<AuthControllerRefreshTokensResponse, AuthControllerRefreshTokensError, Options<AuthControllerRefreshTokensData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerRefreshTokens({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register a new user
 */
export const userControllerRegisterMutation = (options?: Partial<Options<UserControllerRegisterData>>): UseMutationOptions<UserControllerRegisterResponse, UserControllerRegisterError, Options<UserControllerRegisterData>> => {
    const mutationOptions: UseMutationOptions<UserControllerRegisterResponse, UserControllerRegisterError, Options<UserControllerRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await userControllerRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const userControllerGetMeQueryKey = (options?: Options<UserControllerGetMeData>) => createQueryKey('userControllerGetMe', options);

/**
 * Get current user profile
 */
export const userControllerGetMeOptions = (options?: Options<UserControllerGetMeData>) => queryOptions<UserControllerGetMeResponse, DefaultError, UserControllerGetMeResponse, ReturnType<typeof userControllerGetMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await userControllerGetMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: userControllerGetMeQueryKey(options)
});

/**
 * Update current user profile
 */
export const userControllerUpdateMeMutation = (options?: Partial<Options<UserControllerUpdateMeData>>): UseMutationOptions<UserControllerUpdateMeResponse, UserControllerUpdateMeError, Options<UserControllerUpdateMeData>> => {
    const mutationOptions: UseMutationOptions<UserControllerUpdateMeResponse, UserControllerUpdateMeError, Options<UserControllerUpdateMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await userControllerUpdateMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const projectControllerListProjectsQueryKey = (options?: Options<ProjectControllerListProjectsData>) => createQueryKey('projectControllerListProjects', options);

/**
 * List my projects
 */
export const projectControllerListProjectsOptions = (options?: Options<ProjectControllerListProjectsData>) => queryOptions<ProjectControllerListProjectsResponse, DefaultError, ProjectControllerListProjectsResponse, ReturnType<typeof projectControllerListProjectsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await projectControllerListProjects({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: projectControllerListProjectsQueryKey(options)
});

/**
 * Create project
 */
export const projectControllerCreateProjectMutation = (options?: Partial<Options<ProjectControllerCreateProjectData>>): UseMutationOptions<ProjectControllerCreateProjectResponse, ProjectControllerCreateProjectError, Options<ProjectControllerCreateProjectData>> => {
    const mutationOptions: UseMutationOptions<ProjectControllerCreateProjectResponse, ProjectControllerCreateProjectError, Options<ProjectControllerCreateProjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await projectControllerCreateProject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update project
 */
export const projectControllerUpdateProjectMutation = (options?: Partial<Options<ProjectControllerUpdateProjectData>>): UseMutationOptions<ProjectControllerUpdateProjectResponse, ProjectControllerUpdateProjectError, Options<ProjectControllerUpdateProjectData>> => {
    const mutationOptions: UseMutationOptions<ProjectControllerUpdateProjectResponse, ProjectControllerUpdateProjectError, Options<ProjectControllerUpdateProjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await projectControllerUpdateProject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Add project member (owner only)
 */
export const projectControllerAddMemberMutation = (options?: Partial<Options<ProjectControllerAddMemberData>>): UseMutationOptions<ProjectControllerAddMemberResponse, ProjectControllerAddMemberError, Options<ProjectControllerAddMemberData>> => {
    const mutationOptions: UseMutationOptions<ProjectControllerAddMemberResponse, ProjectControllerAddMemberError, Options<ProjectControllerAddMemberData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await projectControllerAddMember({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remove project member (owner only)
 */
export const projectControllerRemoveMemberMutation = (options?: Partial<Options<ProjectControllerRemoveMemberData>>): UseMutationOptions<ProjectControllerRemoveMemberResponse, ProjectControllerRemoveMemberError, Options<ProjectControllerRemoveMemberData>> => {
    const mutationOptions: UseMutationOptions<ProjectControllerRemoveMemberResponse, ProjectControllerRemoveMemberError, Options<ProjectControllerRemoveMemberData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await projectControllerRemoveMember({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
