// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AppControllerGetHelloData, AppControllerGetHelloResponses, AuthControllerLoginWithProviderData, AuthControllerLoginWithProviderErrors, AuthControllerLoginWithProviderResponses, AuthControllerRefreshTokensData, AuthControllerRefreshTokensErrors, AuthControllerRefreshTokensResponses, ProjectControllerAddMemberData, ProjectControllerAddMemberErrors, ProjectControllerAddMemberResponses, ProjectControllerCreateProjectData, ProjectControllerCreateProjectErrors, ProjectControllerCreateProjectResponses, ProjectControllerListProjectsData, ProjectControllerListProjectsResponses, ProjectControllerRemoveMemberData, ProjectControllerRemoveMemberErrors, ProjectControllerRemoveMemberResponses, ProjectControllerUpdateProjectData, ProjectControllerUpdateProjectErrors, ProjectControllerUpdateProjectResponses, UserControllerGetMeData, UserControllerGetMeErrors, UserControllerGetMeResponses, UserControllerRegisterData, UserControllerRegisterErrors, UserControllerRegisterResponses, UserControllerUpdateMeData, UserControllerUpdateMeErrors, UserControllerUpdateMeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>) => (options?.client ?? client).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Login with Google access token
 */
export const authControllerLoginWithProvider = <ThrowOnError extends boolean = false>(options: Options<AuthControllerLoginWithProviderData, ThrowOnError>) => (options.client ?? client).post<AuthControllerLoginWithProviderResponses, AuthControllerLoginWithProviderErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh access/refresh tokens
 */
export const authControllerRefreshTokens = <ThrowOnError extends boolean = false>(options: Options<AuthControllerRefreshTokensData, ThrowOnError>) => (options.client ?? client).post<AuthControllerRefreshTokensResponses, AuthControllerRefreshTokensErrors, ThrowOnError>({
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register a new user
 */
export const userControllerRegister = <ThrowOnError extends boolean = false>(options: Options<UserControllerRegisterData, ThrowOnError>) => (options.client ?? client).post<UserControllerRegisterResponses, UserControllerRegisterErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get current user profile
 */
export const userControllerGetMe = <ThrowOnError extends boolean = false>(options?: Options<UserControllerGetMeData, ThrowOnError>) => (options?.client ?? client).get<UserControllerGetMeResponses, UserControllerGetMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options
});

/**
 * Update current user profile
 */
export const userControllerUpdateMe = <ThrowOnError extends boolean = false>(options: Options<UserControllerUpdateMeData, ThrowOnError>) => (options.client ?? client).put<UserControllerUpdateMeResponses, UserControllerUpdateMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List my projects
 */
export const projectControllerListProjects = <ThrowOnError extends boolean = false>(options?: Options<ProjectControllerListProjectsData, ThrowOnError>) => (options?.client ?? client).get<ProjectControllerListProjectsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects',
    ...options
});

/**
 * Create project
 */
export const projectControllerCreateProject = <ThrowOnError extends boolean = false>(options: Options<ProjectControllerCreateProjectData, ThrowOnError>) => (options.client ?? client).post<ProjectControllerCreateProjectResponses, ProjectControllerCreateProjectErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update project
 */
export const projectControllerUpdateProject = <ThrowOnError extends boolean = false>(options: Options<ProjectControllerUpdateProjectData, ThrowOnError>) => (options.client ?? client).put<ProjectControllerUpdateProjectResponses, ProjectControllerUpdateProjectErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add project member (owner only)
 */
export const projectControllerAddMember = <ThrowOnError extends boolean = false>(options: Options<ProjectControllerAddMemberData, ThrowOnError>) => (options.client ?? client).post<ProjectControllerAddMemberResponses, ProjectControllerAddMemberErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove project member (owner only)
 */
export const projectControllerRemoveMember = <ThrowOnError extends boolean = false>(options: Options<ProjectControllerRemoveMemberData, ThrowOnError>) => (options.client ?? client).post<ProjectControllerRemoveMemberResponses, ProjectControllerRemoveMemberErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/projects/{id}/members/remove',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
