// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetProjectsData, GetProjectsErrors, GetProjectsResponses, GetUsersMeData, GetUsersMeErrors, GetUsersMeResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthRefreshData, PostAuthRefreshErrors, PostAuthRefreshResponses, PostAuthSwitchTeamData, PostAuthSwitchTeamErrors, PostAuthSwitchTeamResponses, PostDebugUsersPlanData, PostDebugUsersPlanErrors, PostDebugUsersPlanResponses, PostProjectsByIdMembersData, PostProjectsByIdMembersErrors, PostProjectsByIdMembersRemoveData, PostProjectsByIdMembersRemoveErrors, PostProjectsByIdMembersRemoveResponses, PostProjectsByIdMembersResponses, PostProjectsData, PostProjectsErrors, PostProjectsResponses, PostTeamsData, PostTeamsErrors, PostTeamsResponses, PostUsersRegisterData, PostUsersRegisterErrors, PostUsersRegisterResponses, PutProjectsByIdData, PutProjectsByIdErrors, PutProjectsByIdResponses, PutUsersMeData, PutUsersMeErrors, PutUsersMeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login with Google access token
 *
 * Login with Google access token
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh access/refresh tokens
 *
 * Refresh access/refresh tokens
 */
export const postAuthRefresh = <ThrowOnError extends boolean = false>(options: Options<PostAuthRefreshData, ThrowOnError>) => (options.client ?? client).post<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError>({
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Switch active team and get new tokens
 *
 * Switch active team and get new tokens
 */
export const postAuthSwitchTeam = <ThrowOnError extends boolean = false>(options: Options<PostAuthSwitchTeamData, ThrowOnError>) => (options.client ?? client).post<PostAuthSwitchTeamResponses, PostAuthSwitchTeamErrors, ThrowOnError>({
    url: '/auth/switch-team',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Debug: update user personal plan (free|pro)
 *
 * Debug: update user personal plan (free|pro)
 */
export const postDebugUsersPlan = <ThrowOnError extends boolean = false>(options: Options<PostDebugUsersPlanData, ThrowOnError>) => (options.client ?? client).post<PostDebugUsersPlanResponses, PostDebugUsersPlanErrors, ThrowOnError>({
    url: '/debug/users/plan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List my projects
 *
 * List my projects
 */
export const getProjects = <ThrowOnError extends boolean = false>(options?: Options<GetProjectsData, ThrowOnError>) => (options?.client ?? client).get<GetProjectsResponses, GetProjectsErrors, ThrowOnError>({ url: '/projects', ...options });

/**
 * Create project
 *
 * Create project
 */
export const postProjects = <ThrowOnError extends boolean = false>(options: Options<PostProjectsData, ThrowOnError>) => (options.client ?? client).post<PostProjectsResponses, PostProjectsErrors, ThrowOnError>({
    url: '/projects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update project
 *
 * Update project
 */
export const putProjectsById = <ThrowOnError extends boolean = false>(options: Options<PutProjectsByIdData, ThrowOnError>) => (options.client ?? client).put<PutProjectsByIdResponses, PutProjectsByIdErrors, ThrowOnError>({
    url: '/projects/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add project member (owner only)
 *
 * Add project member (owner only)
 */
export const postProjectsByIdMembers = <ThrowOnError extends boolean = false>(options: Options<PostProjectsByIdMembersData, ThrowOnError>) => (options.client ?? client).post<PostProjectsByIdMembersResponses, PostProjectsByIdMembersErrors, ThrowOnError>({
    url: '/projects/{id}/members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove project member (owner only)
 *
 * Remove project member (owner only)
 */
export const postProjectsByIdMembersRemove = <ThrowOnError extends boolean = false>(options: Options<PostProjectsByIdMembersRemoveData, ThrowOnError>) => (options.client ?? client).post<PostProjectsByIdMembersRemoveResponses, PostProjectsByIdMembersRemoveErrors, ThrowOnError>({
    url: '/projects/{id}/members/remove',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a team (org workspace)
 *
 * Create a team (org workspace)
 */
export const postTeams = <ThrowOnError extends boolean = false>(options: Options<PostTeamsData, ThrowOnError>) => (options.client ?? client).post<PostTeamsResponses, PostTeamsErrors, ThrowOnError>({
    url: '/teams',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get current user profile
 *
 * Get current user profile
 */
export const getUsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>) => (options?.client ?? client).get<GetUsersMeResponses, GetUsersMeErrors, ThrowOnError>({ url: '/users/me', ...options });

/**
 * Update current user profile
 *
 * Update current user profile
 */
export const putUsersMe = <ThrowOnError extends boolean = false>(options: Options<PutUsersMeData, ThrowOnError>) => (options.client ?? client).put<PutUsersMeResponses, PutUsersMeErrors, ThrowOnError>({
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register a new user
 *
 * Register a new user
 */
export const postUsersRegister = <ThrowOnError extends boolean = false>(options: Options<PostUsersRegisterData, ThrowOnError>) => (options.client ?? client).post<PostUsersRegisterResponses, PostUsersRegisterErrors, ThrowOnError>({
    url: '/users/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
