// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ResponseEnvelopeDto = {
    data: unknown;
    timestamp: string;
    requestId?: string;
    path?: string;
};

export type RefreshTokensDto = {
    refreshToken: string;
};

export type ProviderLoginDto = {
    accessToken: string;
};

export type CreateProjectDto = {
    name: string;
    description?: string;
    languages?: Array<string>;
    defaultLanguage?: string;
    slug?: string;
};

export type UpdateProjectDto = {
    name?: string;
    description?: string;
    languages?: Array<string>;
    defaultLanguage?: string;
    slug?: string;
};

export type AddMemberDto = {
    userId: string;
    role: 'owner' | 'editor' | 'viewer';
};

export type ProjectDto = {
    id: string;
    name: string;
    description: string | unknown;
    languages: Array<string> | unknown;
    defaultLanguage: string | unknown;
    slug: string;
    ownerId: string;
    createdAt: string | unknown;
    updatedAt: string | unknown;
};

export type ListProjectsResponseDto = {
    items: Array<{
        id: string;
        name: string;
        description: string | unknown;
        languages: Array<string> | unknown;
        defaultLanguage: string | unknown;
        slug: string;
        ownerId: string;
        createdAt: string | unknown;
        updatedAt: string | unknown;
    }>;
    meta: {
        index: number;
        pageSize: number;
        hasNext: boolean;
        totalCount: number;
        totalPageCount: number;
    };
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    /**
     * Returns a greeting string
     */
    200: ResponseEnvelopeDto & {
        data?: string;
    };
};

export type AppControllerGetHelloResponse = AppControllerGetHelloResponses[keyof AppControllerGetHelloResponses];

export type AuthControllerLoginWithProviderData = {
    /**
     * Provider access token payload
     */
    body: ProviderLoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginWithProviderErrors = {
    /**
     * Invalid payload
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
};

export type AuthControllerLoginWithProviderError = AuthControllerLoginWithProviderErrors[keyof AuthControllerLoginWithProviderErrors];

export type AuthControllerLoginWithProviderResponses = {
    /**
     * Issued token pair
     */
    200: ResponseEnvelopeDto & {
        data?: {
            accessToken: string;
            refreshToken: string;
        };
    };
};

export type AuthControllerLoginWithProviderResponse = AuthControllerLoginWithProviderResponses[keyof AuthControllerLoginWithProviderResponses];

export type AuthControllerRefreshTokensData = {
    /**
     * Refresh token payload
     */
    body: RefreshTokensDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshTokensErrors = {
    /**
     * Invalid payload
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
};

export type AuthControllerRefreshTokensError = AuthControllerRefreshTokensErrors[keyof AuthControllerRefreshTokensErrors];

export type AuthControllerRefreshTokensResponses = {
    /**
     * New token pair
     */
    200: ResponseEnvelopeDto & {
        data?: {
            accessToken: string;
            refreshToken: string;
        };
    };
};

export type AuthControllerRefreshTokensResponse = AuthControllerRefreshTokensResponses[keyof AuthControllerRefreshTokensResponses];

export type UserControllerRegisterData = {
    /**
     * User registration payload
     */
    body: {
        id: string;
        email: string;
        fullName?: string;
        avatarUrl?: string;
        plan?: string;
    };
    path?: never;
    query?: never;
    url: '/users/register';
};

export type UserControllerRegisterErrors = {
    /**
     * Invalid request
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
    /**
     * User already exists
     */
    409: unknown;
};

export type UserControllerRegisterError = UserControllerRegisterErrors[keyof UserControllerRegisterErrors];

export type UserControllerRegisterResponses = {
    /**
     * Created user and JWT token
     */
    200: ResponseEnvelopeDto & {
        data?: {
            user?: {
                id: string;
                email?: string | unknown;
                fullName?: string | unknown;
                avatarUrl?: string | unknown;
                plan?: string | unknown;
                createdAt?: string | unknown;
                updatedAt?: string | unknown;
            };
            accessToken?: string;
            refreshToken?: string;
        };
    };
};

export type UserControllerRegisterResponse = UserControllerRegisterResponses[keyof UserControllerRegisterResponses];

export type UserControllerGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UserControllerGetMeErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type UserControllerGetMeResponses = {
    /**
     * Current user
     */
    200: ResponseEnvelopeDto & {
        data?: {
            id: string;
            email?: string | unknown;
            fullName?: string | unknown;
            avatarUrl?: string | unknown;
            plan?: string | unknown;
            createdAt?: string | unknown;
            updatedAt?: string | unknown;
        };
    };
};

export type UserControllerGetMeResponse = UserControllerGetMeResponses[keyof UserControllerGetMeResponses];

export type UserControllerUpdateMeData = {
    /**
     * User update payload
     */
    body: {
        fullName?: string;
        avatarUrl?: string;
        plan?: string;
    };
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UserControllerUpdateMeErrors = {
    /**
     * Invalid request
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
    /**
     * Unauthorized
     */
    401: unknown;
};

export type UserControllerUpdateMeError = UserControllerUpdateMeErrors[keyof UserControllerUpdateMeErrors];

export type UserControllerUpdateMeResponses = {
    /**
     * Updated user
     */
    200: ResponseEnvelopeDto & {
        data?: {
            id: string;
            email?: string | unknown;
            fullName?: string | unknown;
            avatarUrl?: string | unknown;
            plan?: string | unknown;
            createdAt?: string | unknown;
            updatedAt?: string | unknown;
        };
    };
};

export type UserControllerUpdateMeResponse = UserControllerUpdateMeResponses[keyof UserControllerUpdateMeResponses];

export type ProjectControllerListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Zero-based page index
         */
        index?: number;
        /**
         * Number of projects per page
         */
        pageSize?: number;
    };
    url: '/projects';
};

export type ProjectControllerListProjectsResponses = {
    /**
     * Projects list
     */
    200: ResponseEnvelopeDto & {
        data?: ListProjectsResponseDto;
    };
};

export type ProjectControllerListProjectsResponse = ProjectControllerListProjectsResponses[keyof ProjectControllerListProjectsResponses];

export type ProjectControllerCreateProjectData = {
    /**
     * Project creation payload
     */
    body: CreateProjectDto;
    path?: never;
    query?: never;
    url: '/projects';
};

export type ProjectControllerCreateProjectErrors = {
    /**
     * Invalid payload
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
    /**
     * Plan limit exceeded
     */
    403: {
        statusCode: number;
        message: string;
        error?: string;
    };
    /**
     * Slug conflict
     */
    409: {
        statusCode: number;
        message: string;
        error?: string;
    };
};

export type ProjectControllerCreateProjectError = ProjectControllerCreateProjectErrors[keyof ProjectControllerCreateProjectErrors];

export type ProjectControllerCreateProjectResponses = {
    /**
     * Created project
     */
    200: ResponseEnvelopeDto & {
        data?: ProjectDto;
    };
};

export type ProjectControllerCreateProjectResponse = ProjectControllerCreateProjectResponses[keyof ProjectControllerCreateProjectResponses];

export type ProjectControllerUpdateProjectData = {
    /**
     * Project update payload
     */
    body: UpdateProjectDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type ProjectControllerUpdateProjectErrors = {
    /**
     * Invalid payload
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
    /**
     * Unauthorized
     */
    401: {
        statusCode: number;
        message: string;
        error?: string;
    };
};

export type ProjectControllerUpdateProjectError = ProjectControllerUpdateProjectErrors[keyof ProjectControllerUpdateProjectErrors];

export type ProjectControllerUpdateProjectResponses = {
    /**
     * Updated project
     */
    200: ResponseEnvelopeDto & {
        data?: ProjectDto;
    };
};

export type ProjectControllerUpdateProjectResponse = ProjectControllerUpdateProjectResponses[keyof ProjectControllerUpdateProjectResponses];

export type ProjectControllerAddMemberData = {
    /**
     * Add member payload
     */
    body: AddMemberDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/members';
};

export type ProjectControllerAddMemberErrors = {
    /**
     * Invalid payload
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
};

export type ProjectControllerAddMemberError = ProjectControllerAddMemberErrors[keyof ProjectControllerAddMemberErrors];

export type ProjectControllerAddMemberResponses = {
    /**
     * Member added
     */
    200: ResponseEnvelopeDto & {
        data?: unknown;
    };
};

export type ProjectControllerAddMemberResponse = ProjectControllerAddMemberResponses[keyof ProjectControllerAddMemberResponses];

export type ProjectControllerRemoveMemberData = {
    /**
     * Remove member payload
     */
    body: {
        userId: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/members/remove';
};

export type ProjectControllerRemoveMemberErrors = {
    /**
     * Invalid payload
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
};

export type ProjectControllerRemoveMemberError = ProjectControllerRemoveMemberErrors[keyof ProjectControllerRemoveMemberErrors];

export type ProjectControllerRemoveMemberResponses = {
    /**
     * Member removed
     */
    200: ResponseEnvelopeDto & {
        data?: unknown;
    };
};

export type ProjectControllerRemoveMemberResponse = ProjectControllerRemoveMemberResponses[keyof ProjectControllerRemoveMemberResponses];
