// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreateProjectDto = {
    name: string;
    description?: string;
    languages?: Array<string>;
    defaultLanguage?: string;
    slug?: string;
};

export type UpdateProjectDto = {
    name?: string;
    description?: string;
    languages?: Array<string>;
    defaultLanguage?: string;
    slug?: string;
};

export type AddMemberDto = {
    userId: string;
    role: 'owner' | 'editor' | 'viewer';
};

export type ProjectDto = {
    id: string;
    name: string;
    description: string | unknown;
    languages: Array<string> | unknown;
    defaultLanguage: string | unknown;
    slug: string;
    ownerId: string;
    createdAt: string | unknown;
    updatedAt: string | unknown;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    /**
     * Returns a greeting string
     */
    200: unknown;
};

export type UserControllerRegisterData = {
    /**
     * User registration payload
     */
    body: {
        id: string;
        email: string;
        fullName?: string;
        avatarUrl?: string;
        plan?: string;
    };
    path?: never;
    query?: never;
    url: '/users/register';
};

export type UserControllerRegisterErrors = {
    /**
     * Invalid request
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
    /**
     * User already exists
     */
    409: unknown;
};

export type UserControllerRegisterError = UserControllerRegisterErrors[keyof UserControllerRegisterErrors];

export type UserControllerRegisterResponses = {
    /**
     * Created user and JWT token
     */
    200: {
        user?: {
            id: string;
            email?: string | unknown;
            fullName?: string | unknown;
            avatarUrl?: string | unknown;
            plan?: string | unknown;
            createdAt?: string | unknown;
            updatedAt?: string | unknown;
        };
        accessToken?: string;
        refreshToken?: string;
    };
};

export type UserControllerRegisterResponse = UserControllerRegisterResponses[keyof UserControllerRegisterResponses];

export type UserControllerGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UserControllerGetMeErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type UserControllerGetMeResponses = {
    /**
     * Current user
     */
    200: {
        id: string;
        email?: string | unknown;
        fullName?: string | unknown;
        avatarUrl?: string | unknown;
        plan?: string | unknown;
        createdAt?: string | unknown;
        updatedAt?: string | unknown;
    };
};

export type UserControllerGetMeResponse = UserControllerGetMeResponses[keyof UserControllerGetMeResponses];

export type UserControllerUpdateMeData = {
    /**
     * User update payload
     */
    body: {
        fullName?: string;
        avatarUrl?: string;
        plan?: string;
    };
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UserControllerUpdateMeErrors = {
    /**
     * Invalid request
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
    /**
     * Unauthorized
     */
    401: unknown;
};

export type UserControllerUpdateMeError = UserControllerUpdateMeErrors[keyof UserControllerUpdateMeErrors];

export type UserControllerUpdateMeResponses = {
    /**
     * Updated user
     */
    200: {
        id: string;
        email?: string | unknown;
        fullName?: string | unknown;
        avatarUrl?: string | unknown;
        plan?: string | unknown;
        createdAt?: string | unknown;
        updatedAt?: string | unknown;
    };
};

export type UserControllerUpdateMeResponse = UserControllerUpdateMeResponses[keyof UserControllerUpdateMeResponses];

export type ProjectControllerListProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects';
};

export type ProjectControllerListProjectsResponses = {
    /**
     * Projects list
     */
    200: Array<ProjectDto>;
};

export type ProjectControllerListProjectsResponse = ProjectControllerListProjectsResponses[keyof ProjectControllerListProjectsResponses];

export type ProjectControllerCreateProjectData = {
    /**
     * Project creation payload
     */
    body: CreateProjectDto;
    path?: never;
    query?: never;
    url: '/projects';
};

export type ProjectControllerCreateProjectErrors = {
    /**
     * Invalid payload
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
    /**
     * Slug conflict
     */
    409: {
        statusCode: number;
        message: string;
        error?: string;
    };
};

export type ProjectControllerCreateProjectError = ProjectControllerCreateProjectErrors[keyof ProjectControllerCreateProjectErrors];

export type ProjectControllerCreateProjectResponses = {
    /**
     * Created project
     */
    200: ProjectDto;
};

export type ProjectControllerCreateProjectResponse = ProjectControllerCreateProjectResponses[keyof ProjectControllerCreateProjectResponses];

export type ProjectControllerUpdateProjectData = {
    /**
     * Project update payload
     */
    body: UpdateProjectDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type ProjectControllerUpdateProjectErrors = {
    /**
     * Invalid payload
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
    /**
     * Unauthorized
     */
    401: {
        statusCode: number;
        message: string;
        error?: string;
    };
};

export type ProjectControllerUpdateProjectError = ProjectControllerUpdateProjectErrors[keyof ProjectControllerUpdateProjectErrors];

export type ProjectControllerUpdateProjectResponses = {
    /**
     * Updated project
     */
    200: ProjectDto;
};

export type ProjectControllerUpdateProjectResponse = ProjectControllerUpdateProjectResponses[keyof ProjectControllerUpdateProjectResponses];

export type ProjectControllerAddMemberData = {
    /**
     * Add member payload
     */
    body: AddMemberDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/members';
};

export type ProjectControllerAddMemberErrors = {
    /**
     * Invalid payload
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
};

export type ProjectControllerAddMemberError = ProjectControllerAddMemberErrors[keyof ProjectControllerAddMemberErrors];

export type ProjectControllerAddMemberResponses = {
    /**
     * Member added
     */
    200: unknown;
};

export type ProjectControllerRemoveMemberData = {
    /**
     * Remove member payload
     */
    body: {
        userId: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/projects/{id}/members/remove';
};

export type ProjectControllerRemoveMemberErrors = {
    /**
     * Invalid payload
     */
    400: {
        statusCode: number;
        message: string;
        error?: string;
    };
};

export type ProjectControllerRemoveMemberError = ProjectControllerRemoveMemberErrors[keyof ProjectControllerRemoveMemberErrors];

export type ProjectControllerRemoveMemberResponses = {
    /**
     * Member removed
     */
    200: unknown;
};
