// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000/api/v1' | 'https://localhost:8000/api/v1' | (string & {});
};

/**
 * Error response structure
 */
export type BackendGoInternalCommonResponseErrorResponse = {
    message?: string;
    path?: string;
    requestId?: string;
    statusCode?: number;
    timestamp?: string;
};

/**
 * Provider access token payload
 */
export type InternalAuthProviderLoginRequest = {
    accessToken: string;
    teamId?: string;
};

/**
 * Refresh token payload
 */
export type InternalAuthRefreshTokensRequest = {
    refreshToken: string;
};

/**
 * Switch team payload
 */
export type InternalAuthSwitchTeamRequest = {
    teamId: string;
};

/**
 * Token pair response
 */
export type InternalAuthTokenPair = {
    accessToken?: string;
    refreshToken?: string;
};

/**
 * Token pair wrapped in response envelope
 */
export type InternalAuthTokenPairResponse = {
    data?: InternalAuthTokenPair;
    timestamp?: string;
};

/**
 * Update plan payload (debug only)
 */
export type InternalDebugUpdateUserPlanRequest = {
    plan: 'free' | 'pro';
    userId?: string;
};

/**
 * Plan updated response
 */
export type InternalDebugUpdateUserPlanResponse = {
    success?: boolean;
};

/**
 * Update user plan response wrapped in response envelope
 */
export type InternalDebugUpdateUserPlanResponseWrapper = {
    data?: InternalDebugUpdateUserPlanResponse;
    timestamp?: string;
};

/**
 * Add member payload
 */
export type InternalProjectAddMemberRequest = {
    role: 'owner' | 'editor' | 'viewer';
    userId: string;
};

/**
 * Project creation payload
 */
export type InternalProjectCreateProjectRequest = {
    defaultLanguage?: string;
    description?: string;
    languages?: Array<string>;
    name: string;
    slug?: string;
};

/**
 * Pagination metadata
 */
export type InternalProjectListProjectsMeta = {
    hasNext?: boolean;
    index?: number;
    pageSize?: number;
    totalCount?: number;
    totalPageCount?: number;
};

/**
 * Project list response
 */
export type InternalProjectListProjectsResponse = {
    items?: Array<InternalProjectProject>;
    meta?: InternalProjectListProjectsMeta;
};

/**
 * Project list wrapped in response envelope
 */
export type InternalProjectListProjectsResponseWrapper = {
    data?: InternalProjectListProjectsResponse;
    timestamp?: string;
};

/**
 * Project details
 */
export type InternalProjectProject = {
    archived?: boolean;
    createdAt?: string;
    defaultLanguage?: string;
    description?: string;
    id?: string;
    languages?: Array<string>;
    name?: string;
    ownerId?: string;
    slug?: string;
    updatedAt?: string;
};

/**
 * Project wrapped in response envelope
 */
export type InternalProjectProjectResponse = {
    data?: InternalProjectProject;
    timestamp?: string;
};

/**
 * Remove member payload
 */
export type InternalProjectRemoveMemberRequest = {
    userId: string;
};

/**
 * Project update payload
 */
export type InternalProjectUpdateProjectRequest = {
    defaultLanguage?: string;
    description?: string;
    languages?: Array<string>;
    name?: string;
    slug?: string;
};

/**
 * Team creation payload
 */
export type InternalTeamCreateTeamRequest = {
    avatarUrl?: string;
    name: string;
};

/**
 * Team details
 */
export type InternalTeamTeam = {
    avatarUrl?: string;
    createdAt?: string;
    id?: string;
    name?: string;
    ownerId?: string;
    personal?: boolean;
    updatedAt?: string;
};

/**
 * Team wrapped in response envelope
 */
export type InternalTeamTeamResponse = {
    data?: InternalTeamTeam;
    timestamp?: string;
};

/**
 * User registration payload
 */
export type InternalUserRegisterUserRequest = {
    avatarUrl?: string;
    email: string;
    fullName?: string;
    id: string;
    plan?: string;
};

/**
 * Created user and JWT token
 */
export type InternalUserRegisterUserResponse = {
    accessToken?: string;
    refreshToken?: string;
    user?: InternalUserUser;
};

/**
 * Registration response wrapped in response envelope
 */
export type InternalUserRegisterUserResponseWrapper = {
    data?: InternalUserRegisterUserResponse;
    timestamp?: string;
};

/**
 * Team information
 */
export type InternalUserTeamInfo = {
    avatarUrl?: string;
    canCreateProject?: boolean;
    memberCount?: number;
    personal?: boolean;
    plan?: string;
    projectCount?: number;
    teamId?: string;
    teamName?: string;
};

/**
 * User update payload
 */
export type InternalUserUpdateUserRequest = {
    avatarUrl?: string;
    fullName?: string;
    plan?: string;
};

/**
 * User profile
 */
export type InternalUserUser = {
    activeTeamId?: string;
    avatarUrl?: string;
    createdAt?: string;
    email?: string;
    fullName?: string;
    id?: string;
    plan?: string;
    teams?: Array<InternalUserTeamInfo>;
    updatedAt?: string;
};

/**
 * User wrapped in response envelope
 */
export type InternalUserUserResponse = {
    data?: InternalUserUser;
    timestamp?: string;
};

export type PostAuthLoginData = {
    /**
     * Provider access token payload
     */
    body: InternalAuthProviderLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: BackendGoInternalCommonResponseErrorResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Issued token pair
     */
    200: InternalAuthTokenPairResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRefreshData = {
    /**
     * Refresh token payload
     */
    body: InternalAuthRefreshTokensRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Bad Request
     */
    400: BackendGoInternalCommonResponseErrorResponse;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * New token pair
     */
    200: InternalAuthTokenPairResponse;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthSwitchTeamData = {
    /**
     * Switch team payload
     */
    body: InternalAuthSwitchTeamRequest;
    path?: never;
    query?: never;
    url: '/auth/switch-team';
};

export type PostAuthSwitchTeamErrors = {
    /**
     * Bad Request
     */
    400: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: BackendGoInternalCommonResponseErrorResponse;
};

export type PostAuthSwitchTeamError = PostAuthSwitchTeamErrors[keyof PostAuthSwitchTeamErrors];

export type PostAuthSwitchTeamResponses = {
    /**
     * New token pair with teamId
     */
    200: InternalAuthTokenPairResponse;
};

export type PostAuthSwitchTeamResponse = PostAuthSwitchTeamResponses[keyof PostAuthSwitchTeamResponses];

export type PostDebugUsersPlanData = {
    /**
     * Update plan payload (debug only)
     */
    body: InternalDebugUpdateUserPlanRequest;
    path?: never;
    query?: never;
    url: '/debug/users/plan';
};

export type PostDebugUsersPlanErrors = {
    /**
     * Invalid request
     */
    400: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Not allowed in production
     */
    403: BackendGoInternalCommonResponseErrorResponse;
};

export type PostDebugUsersPlanError = PostDebugUsersPlanErrors[keyof PostDebugUsersPlanErrors];

export type PostDebugUsersPlanResponses = {
    /**
     * Plan updated
     */
    200: InternalDebugUpdateUserPlanResponseWrapper;
};

export type PostDebugUsersPlanResponse = PostDebugUsersPlanResponses[keyof PostDebugUsersPlanResponses];

export type GetProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page size
         */
        pageSize?: number;
        /**
         * Page index
         */
        index?: number;
        /**
         * Search query
         */
        search?: string;
        /**
         * Filter by status (active, archived)
         */
        status?: string;
        /**
         * Sort order (newest, oldest)
         */
        sort?: string;
    };
    url: '/projects';
};

export type GetProjectsErrors = {
    /**
     * Bad Request
     */
    400: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: BackendGoInternalCommonResponseErrorResponse;
};

export type GetProjectsError = GetProjectsErrors[keyof GetProjectsErrors];

export type GetProjectsResponses = {
    /**
     * Project list
     */
    200: InternalProjectListProjectsResponseWrapper;
};

export type GetProjectsResponse = GetProjectsResponses[keyof GetProjectsResponses];

export type PostProjectsData = {
    /**
     * Project creation payload
     */
    body: InternalProjectCreateProjectRequest;
    path?: never;
    query?: never;
    url: '/projects';
};

export type PostProjectsErrors = {
    /**
     * Invalid payload
     */
    400: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Project limit exceeded
     */
    403: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Project conflict
     */
    409: BackendGoInternalCommonResponseErrorResponse;
};

export type PostProjectsError = PostProjectsErrors[keyof PostProjectsErrors];

export type PostProjectsResponses = {
    /**
     * Created project
     */
    201: InternalProjectProjectResponse;
};

export type PostProjectsResponse = PostProjectsResponses[keyof PostProjectsResponses];

export type PutProjectsByIdData = {
    /**
     * Project update payload
     */
    body: InternalProjectUpdateProjectRequest;
    path: {
        /**
         * Project ID
         */
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type PutProjectsByIdErrors = {
    /**
     * Invalid payload
     */
    400: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Forbidden
     */
    403: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Project not found
     */
    404: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Project conflict
     */
    409: BackendGoInternalCommonResponseErrorResponse;
};

export type PutProjectsByIdError = PutProjectsByIdErrors[keyof PutProjectsByIdErrors];

export type PutProjectsByIdResponses = {
    /**
     * Updated project
     */
    200: InternalProjectProjectResponse;
};

export type PutProjectsByIdResponse = PutProjectsByIdResponses[keyof PutProjectsByIdResponses];

export type PostProjectsByIdMembersData = {
    /**
     * Add member payload
     */
    body: InternalProjectAddMemberRequest;
    path: {
        /**
         * Project ID
         */
        id: string;
    };
    query?: never;
    url: '/projects/{id}/members';
};

export type PostProjectsByIdMembersErrors = {
    /**
     * Bad Request
     */
    400: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Forbidden
     */
    403: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Not Found
     */
    404: BackendGoInternalCommonResponseErrorResponse;
};

export type PostProjectsByIdMembersError = PostProjectsByIdMembersErrors[keyof PostProjectsByIdMembersErrors];

export type PostProjectsByIdMembersResponses = {
    /**
     * Member added
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostProjectsByIdMembersResponse = PostProjectsByIdMembersResponses[keyof PostProjectsByIdMembersResponses];

export type PostProjectsByIdMembersRemoveData = {
    /**
     * Remove member payload
     */
    body: InternalProjectRemoveMemberRequest;
    path: {
        /**
         * Project ID
         */
        id: string;
    };
    query?: never;
    url: '/projects/{id}/members/remove';
};

export type PostProjectsByIdMembersRemoveErrors = {
    /**
     * Invalid payload
     */
    400: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Forbidden
     */
    403: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Project not found
     */
    404: BackendGoInternalCommonResponseErrorResponse;
};

export type PostProjectsByIdMembersRemoveError = PostProjectsByIdMembersRemoveErrors[keyof PostProjectsByIdMembersRemoveErrors];

export type PostProjectsByIdMembersRemoveResponses = {
    /**
     * Member removed
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostProjectsByIdMembersRemoveResponse = PostProjectsByIdMembersRemoveResponses[keyof PostProjectsByIdMembersRemoveResponses];

export type PostTeamsData = {
    /**
     * Team creation payload
     */
    body: InternalTeamCreateTeamRequest;
    path?: never;
    query?: never;
    url: '/teams';
};

export type PostTeamsErrors = {
    /**
     * Invalid payload
     */
    400: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: BackendGoInternalCommonResponseErrorResponse;
};

export type PostTeamsError = PostTeamsErrors[keyof PostTeamsErrors];

export type PostTeamsResponses = {
    /**
     * Team created
     */
    201: InternalTeamTeamResponse;
};

export type PostTeamsResponse = PostTeamsResponses[keyof PostTeamsResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeErrors = {
    /**
     * Unauthorized
     */
    401: BackendGoInternalCommonResponseErrorResponse;
};

export type GetUsersMeError = GetUsersMeErrors[keyof GetUsersMeErrors];

export type GetUsersMeResponses = {
    /**
     * Current user
     */
    200: InternalUserUserResponse;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type PutUsersMeData = {
    /**
     * User update payload
     */
    body: InternalUserUpdateUserRequest;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type PutUsersMeErrors = {
    /**
     * Invalid request
     */
    400: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Unauthorized
     */
    401: BackendGoInternalCommonResponseErrorResponse;
};

export type PutUsersMeError = PutUsersMeErrors[keyof PutUsersMeErrors];

export type PutUsersMeResponses = {
    /**
     * Updated user
     */
    200: InternalUserUserResponse;
};

export type PutUsersMeResponse = PutUsersMeResponses[keyof PutUsersMeResponses];

export type PostUsersRegisterData = {
    /**
     * User registration payload
     */
    body: InternalUserRegisterUserRequest;
    path?: never;
    query?: never;
    url: '/users/register';
};

export type PostUsersRegisterErrors = {
    /**
     * Bad Request
     */
    400: BackendGoInternalCommonResponseErrorResponse;
    /**
     * Conflict
     */
    409: BackendGoInternalCommonResponseErrorResponse;
};

export type PostUsersRegisterError = PostUsersRegisterErrors[keyof PostUsersRegisterErrors];

export type PostUsersRegisterResponses = {
    /**
     * Created user and JWT token
     */
    200: InternalUserRegisterUserResponseWrapper;
};

export type PostUsersRegisterResponse = PostUsersRegisterResponses[keyof PostUsersRegisterResponses];
