// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Error response structure
 */
export const zBackendGoInternalCommonResponseErrorResponse = z.object({
    message: z.optional(z.string()),
    path: z.optional(z.string()),
    requestId: z.optional(z.string()),
    statusCode: z.optional(z.int()),
    timestamp: z.optional(z.string())
});

/**
 * Provider access token payload
 */
export const zInternalAuthProviderLoginRequest = z.object({
    accessToken: z.string().min(1),
    teamId: z.optional(z.string())
});

/**
 * Refresh token payload
 */
export const zInternalAuthRefreshTokensRequest = z.object({
    refreshToken: z.string()
});

/**
 * Switch team payload
 */
export const zInternalAuthSwitchTeamRequest = z.object({
    teamId: z.string()
});

/**
 * Token pair response
 */
export const zInternalAuthTokenPair = z.object({
    accessToken: z.optional(z.string()),
    refreshToken: z.optional(z.string())
});

/**
 * Token pair wrapped in response envelope
 */
export const zInternalAuthTokenPairResponse = z.object({
    data: z.optional(zInternalAuthTokenPair),
    timestamp: z.optional(z.string())
});

/**
 * Update plan payload (debug only)
 */
export const zInternalDebugUpdateUserPlanRequest = z.object({
    plan: z.enum(['free', 'pro']),
    userId: z.optional(z.string())
});

/**
 * Plan updated response
 */
export const zInternalDebugUpdateUserPlanResponse = z.object({
    success: z.optional(z.boolean())
});

/**
 * Update user plan response wrapped in response envelope
 */
export const zInternalDebugUpdateUserPlanResponseWrapper = z.object({
    data: z.optional(zInternalDebugUpdateUserPlanResponse),
    timestamp: z.optional(z.string())
});

/**
 * Add member payload
 */
export const zInternalProjectAddMemberRequest = z.object({
    role: z.enum([
        'owner',
        'editor',
        'viewer'
    ]),
    userId: z.string()
});

/**
 * Project creation payload
 */
export const zInternalProjectCreateProjectRequest = z.object({
    defaultLanguage: z.optional(z.string()),
    description: z.optional(z.string()),
    languages: z.optional(z.array(z.string())),
    name: z.string().min(1),
    slug: z.optional(z.string())
});

/**
 * Pagination metadata
 */
export const zInternalProjectListProjectsMeta = z.object({
    hasNext: z.optional(z.boolean()),
    index: z.optional(z.int()),
    pageSize: z.optional(z.int()),
    totalCount: z.optional(z.int()),
    totalPageCount: z.optional(z.int())
});

/**
 * Project details
 */
export const zInternalProjectProject = z.object({
    archived: z.optional(z.boolean()),
    createdAt: z.optional(z.string()),
    defaultLanguage: z.optional(z.string()),
    description: z.optional(z.string()),
    id: z.optional(z.string()),
    languages: z.optional(z.array(z.string())),
    name: z.optional(z.string()),
    ownerId: z.optional(z.string()),
    slug: z.optional(z.string()),
    updatedAt: z.optional(z.string())
});

/**
 * Project list response
 */
export const zInternalProjectListProjectsResponse = z.object({
    items: z.optional(z.array(zInternalProjectProject)),
    meta: z.optional(zInternalProjectListProjectsMeta)
});

/**
 * Project list wrapped in response envelope
 */
export const zInternalProjectListProjectsResponseWrapper = z.object({
    data: z.optional(zInternalProjectListProjectsResponse),
    timestamp: z.optional(z.string())
});

/**
 * Project wrapped in response envelope
 */
export const zInternalProjectProjectResponse = z.object({
    data: z.optional(zInternalProjectProject),
    timestamp: z.optional(z.string())
});

/**
 * Remove member payload
 */
export const zInternalProjectRemoveMemberRequest = z.object({
    userId: z.string()
});

/**
 * Project update payload
 */
export const zInternalProjectUpdateProjectRequest = z.object({
    defaultLanguage: z.optional(z.string()),
    description: z.optional(z.string()),
    languages: z.optional(z.array(z.string())),
    name: z.optional(z.string().min(1)),
    slug: z.optional(z.string())
});

/**
 * Team creation payload
 */
export const zInternalTeamCreateTeamRequest = z.object({
    avatarUrl: z.optional(z.string()),
    name: z.string().min(1)
});

/**
 * Team details
 */
export const zInternalTeamTeam = z.object({
    avatarUrl: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    id: z.optional(z.string()),
    name: z.optional(z.string()),
    ownerId: z.optional(z.string()),
    personal: z.optional(z.boolean()),
    updatedAt: z.optional(z.string())
});

/**
 * Team wrapped in response envelope
 */
export const zInternalTeamTeamResponse = z.object({
    data: z.optional(zInternalTeamTeam),
    timestamp: z.optional(z.string())
});

/**
 * User registration payload
 */
export const zInternalUserRegisterUserRequest = z.object({
    avatarUrl: z.optional(z.string()),
    email: z.string(),
    fullName: z.optional(z.string()),
    id: z.string(),
    plan: z.optional(z.string())
});

/**
 * Team information
 */
export const zInternalUserTeamInfo = z.object({
    avatarUrl: z.optional(z.string()),
    canCreateProject: z.optional(z.boolean()),
    memberCount: z.optional(z.int()),
    personal: z.optional(z.boolean()),
    plan: z.optional(z.string()),
    projectCount: z.optional(z.int()),
    teamId: z.optional(z.string()),
    teamName: z.optional(z.string())
});

/**
 * User update payload
 */
export const zInternalUserUpdateUserRequest = z.object({
    avatarUrl: z.optional(z.string()),
    fullName: z.optional(z.string()),
    plan: z.optional(z.string())
});

/**
 * User profile
 */
export const zInternalUserUser = z.object({
    activeTeamId: z.optional(z.string()),
    avatarUrl: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    email: z.optional(z.string()),
    fullName: z.optional(z.string()),
    id: z.optional(z.string()),
    plan: z.optional(z.string()),
    teams: z.optional(z.array(zInternalUserTeamInfo)),
    updatedAt: z.optional(z.string())
});

/**
 * Created user and JWT token
 */
export const zInternalUserRegisterUserResponse = z.object({
    accessToken: z.optional(z.string()),
    refreshToken: z.optional(z.string()),
    user: z.optional(zInternalUserUser)
});

/**
 * Registration response wrapped in response envelope
 */
export const zInternalUserRegisterUserResponseWrapper = z.object({
    data: z.optional(zInternalUserRegisterUserResponse),
    timestamp: z.optional(z.string())
});

/**
 * User wrapped in response envelope
 */
export const zInternalUserUserResponse = z.object({
    data: z.optional(zInternalUserUser),
    timestamp: z.optional(z.string())
});

export const zPostAuthLoginData = z.object({
    body: zInternalAuthProviderLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Issued token pair
 */
export const zPostAuthLoginResponse = zInternalAuthTokenPairResponse;

export const zPostAuthRefreshData = z.object({
    body: zInternalAuthRefreshTokensRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * New token pair
 */
export const zPostAuthRefreshResponse = zInternalAuthTokenPairResponse;

export const zPostAuthSwitchTeamData = z.object({
    body: zInternalAuthSwitchTeamRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * New token pair with teamId
 */
export const zPostAuthSwitchTeamResponse = zInternalAuthTokenPairResponse;

export const zPostDebugUsersPlanData = z.object({
    body: zInternalDebugUpdateUserPlanRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Plan updated
 */
export const zPostDebugUsersPlanResponse = zInternalDebugUpdateUserPlanResponseWrapper;

export const zGetProjectsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        pageSize: z.optional(z.int()).default(15),
        index: z.optional(z.int()).default(0),
        search: z.optional(z.string()),
        status: z.optional(z.string()),
        sort: z.optional(z.string()).default('newest')
    }))
});

/**
 * Project list
 */
export const zGetProjectsResponse = zInternalProjectListProjectsResponseWrapper;

export const zPostProjectsData = z.object({
    body: zInternalProjectCreateProjectRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created project
 */
export const zPostProjectsResponse = zInternalProjectProjectResponse;

export const zPutProjectsByIdData = z.object({
    body: zInternalProjectUpdateProjectRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Updated project
 */
export const zPutProjectsByIdResponse = zInternalProjectProjectResponse;

export const zPostProjectsByIdMembersData = z.object({
    body: zInternalProjectAddMemberRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Member added
 */
export const zPostProjectsByIdMembersResponse = z.record(z.string(), z.unknown());

export const zPostProjectsByIdMembersRemoveData = z.object({
    body: zInternalProjectRemoveMemberRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Member removed
 */
export const zPostProjectsByIdMembersRemoveResponse = z.record(z.string(), z.unknown());

export const zPostTeamsData = z.object({
    body: zInternalTeamCreateTeamRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Team created
 */
export const zPostTeamsResponse = zInternalTeamTeamResponse;

export const zGetUsersMeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Current user
 */
export const zGetUsersMeResponse = zInternalUserUserResponse;

export const zPutUsersMeData = z.object({
    body: zInternalUserUpdateUserRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Updated user
 */
export const zPutUsersMeResponse = zInternalUserUserResponse;

export const zPostUsersRegisterData = z.object({
    body: zInternalUserRegisterUserRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created user and JWT token
 */
export const zPostUsersRegisterResponse = zInternalUserRegisterUserResponseWrapper;
