// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCreateProjectDto = z.object({
    name: z.string().min(1).max(200),
    description: z.optional(z.string().max(1000)),
    languages: z.optional(z.array(z.string())),
    defaultLanguage: z.optional(z.string()),
    slug: z.optional(z.string().min(1).max(200))
});

export const zUpdateProjectDto = z.object({
    name: z.optional(z.string().min(1).max(200)),
    description: z.optional(z.string().max(1000)),
    languages: z.optional(z.array(z.string())),
    defaultLanguage: z.optional(z.string()),
    slug: z.optional(z.string().min(1).max(200))
});

export const zAddMemberDto = z.object({
    userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    role: z.enum([
        'owner',
        'editor',
        'viewer'
    ])
});

export const zProjectDto = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    description: z.union([
        z.string(),
        z.unknown()
    ]),
    languages: z.union([
        z.array(z.string()),
        z.unknown()
    ]),
    defaultLanguage: z.union([
        z.string(),
        z.unknown()
    ]),
    slug: z.string(),
    ownerId: z.string(),
    createdAt: z.union([
        z.string(),
        z.unknown()
    ]),
    updatedAt: z.union([
        z.string(),
        z.unknown()
    ])
});

export const zAppControllerGetHelloData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zUserControllerRegisterData = z.object({
    body: z.object({
        id: z.uuid(),
        email: z.email(),
        fullName: z.optional(z.string()),
        avatarUrl: z.optional(z.url()),
        plan: z.optional(z.string())
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created user and JWT token
 */
export const zUserControllerRegisterResponse = z.object({
    user: z.optional(z.object({
        id: z.uuid(),
        email: z.optional(z.union([
            z.email(),
            z.unknown()
        ])),
        fullName: z.optional(z.union([
            z.string(),
            z.unknown()
        ])),
        avatarUrl: z.optional(z.union([
            z.url(),
            z.unknown()
        ])),
        plan: z.optional(z.union([
            z.string(),
            z.unknown()
        ])),
        createdAt: z.optional(z.union([
            z.iso.datetime(),
            z.unknown()
        ])),
        updatedAt: z.optional(z.union([
            z.iso.datetime(),
            z.unknown()
        ]))
    })),
    accessToken: z.optional(z.string()),
    refreshToken: z.optional(z.string())
});

export const zUserControllerGetMeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Current user
 */
export const zUserControllerGetMeResponse = z.object({
    id: z.uuid(),
    email: z.optional(z.union([
        z.email(),
        z.unknown()
    ])),
    fullName: z.optional(z.union([
        z.string(),
        z.unknown()
    ])),
    avatarUrl: z.optional(z.union([
        z.url(),
        z.unknown()
    ])),
    plan: z.optional(z.union([
        z.string(),
        z.unknown()
    ])),
    createdAt: z.optional(z.union([
        z.iso.datetime(),
        z.unknown()
    ])),
    updatedAt: z.optional(z.union([
        z.iso.datetime(),
        z.unknown()
    ]))
});

export const zUserControllerUpdateMeData = z.object({
    body: z.object({
        fullName: z.optional(z.string()),
        avatarUrl: z.optional(z.url()),
        plan: z.optional(z.string())
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Updated user
 */
export const zUserControllerUpdateMeResponse = z.object({
    id: z.uuid(),
    email: z.optional(z.union([
        z.email(),
        z.unknown()
    ])),
    fullName: z.optional(z.union([
        z.string(),
        z.unknown()
    ])),
    avatarUrl: z.optional(z.union([
        z.url(),
        z.unknown()
    ])),
    plan: z.optional(z.union([
        z.string(),
        z.unknown()
    ])),
    createdAt: z.optional(z.union([
        z.iso.datetime(),
        z.unknown()
    ])),
    updatedAt: z.optional(z.union([
        z.iso.datetime(),
        z.unknown()
    ]))
});

export const zProjectControllerListProjectsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Projects list
 */
export const zProjectControllerListProjectsResponse = z.array(zProjectDto);

export const zProjectControllerCreateProjectData = z.object({
    body: zCreateProjectDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created project
 */
export const zProjectControllerCreateProjectResponse = zProjectDto;

export const zProjectControllerUpdateProjectData = z.object({
    body: zUpdateProjectDto,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Updated project
 */
export const zProjectControllerUpdateProjectResponse = zProjectDto;

export const zProjectControllerAddMemberData = z.object({
    body: zAddMemberDto,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zProjectControllerRemoveMemberData = z.object({
    body: z.object({
        userId: z.uuid()
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});
